# Generated by Django 3.1.3 on 2021-06-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_clear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UCAS_clear.university'),
        ),
    ]
